### ISSUE TITLE
Make response json

### ISSUE THREAD

**Issue by sabindev** [ZennoLab/capmonstercloud-client-js#7]
The response is not json, idk if this is a bug or this is how it was meant to be, but if its not a bug pls make the response json
This is the response i get:
```CaptchaResult {
  error: undefined,
  solution: {
    answer: [
      true,  true,  true,
      false, true,  false,
      false, false, false
    ],
    metadata: null
  }
}
```

**Comment by azeriker** [comment]
Hi. Response is JS object. What are you expecting? Maybe some use-case where json is more suitable rather object?
