### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by kathleenfelipe** [ZennoLab/capmonstercloud-client-js#8]
Estou tentando utilizar a API, porem está na maioria dos momentos ele traz a resposta: Client network socket disconnected before secure TLS connection was established.

Segue abaixo cod:

export async function recaptchaCPM(): Promise<any> {
  try {
    const APIkey = process.env.toKenCaptchaCapmonster;
    const cmcClient = CapMonsterCloudClientFactory.Create(new ClientOptions({ clientKey: `${APIkey}` }));

    const recaptchaV2ProxylessRequest = new RecaptchaV2ProxylessRequest({
      websiteURL: 'https://cronotacografo.rbmlq.gov.br/certificados/consultar',
      websiteKey: '6LdTMyMUAAAAAOkuh_8aqFSh3C1fM1Ou07ZuHl2X',
      rejectUnauthorized: false
    });
    // process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

    const captchaSolution = await cmcClient.Solve(recaptchaV2ProxylessRequest);
    const gRecaptchaResponse = captchaSolution.solution.gRecaptchaResponse;
    return gRecaptchaResponse;
  } catch (err) {
    throw err;
  }
}

**Comment by azeriker** [comment]
Is it happens sometimes or permanent issue?

**Comment by azeriker** [comment]
Feel free to open new issue if its happens again
