### ISSUE TITLE
I need help solving hCaptcha

### ISSUE THREAD

**Issue by tomnphamns** [ZennoLab/capmonstercloud-client-js#9]
I need help. I used HCaptchaProxylessRequest to solve the discord captcha and I got the solution's information (gRecaptchaResponse, respKey and userAgent). 
But I don't know how can my BOT solve the captcha successfully?
How should these 3 values be used so that the captcha form can be closed and solved successfully?
![image](https://github.com/ZennoLab/capmonstercloud-client-js/assets/141036736/de283412-6bae-4feb-a716-4ca4970f96cc)

I use playwright together with node.js
I look forward to receiving your help

**Comment by azeriker** [comment]
Please open ticket in https://helpdesk.zennolab.com/conversation/new  
Our support team can help you with 3 values and how to use them
